name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
    - uses: daite/go-release-action@v1.16
      with:
        go-version: 1.15
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        project_path: "./cmd/angel"
        binary_name: "angel"
        ldflags: "-s -w"
    - uses: actions/setup-go@v2
    - name: Test
      run: go test -v ./...
